server:
  port: 8000

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: grim123
    password: grim123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true      
    properties:
      hibernate:
        format_sql: true
