server:
  port: 8002

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: grim123
    password: grim123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   
      database: postgresql
    show-sql: true      
    
grpc:
  client:
    product-service:
      address: static://localhost:9002
      negotiationType: plaintext
