
server:
  port: 8001

spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: grim123
    password: grim123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   
      database: postgresql
    show-sql: true      

